-- AlterTable
ALTER TABLE `InscriptionQueueItem` ADD COLUMN `ordinal_id` VARCHAR(191) NULL,
    ADD COLUMN `ordinal_link` VARCHAR(191) NULL,
    MODIFY `state` ENUM('PENDING_PAYMENT', 'TEST_PAYMENT', 'WAITING_INSCRIBED_CONFIRMATION', 'WAITING_PAYMENT_CONFIRMATION', 'PAYMENT_CONFIRMED', 'ERROR', 'INSCRIBED', 'SENT') NOT NULL;
