-- AlterTable
ALTER TABLE `inscriptionqueueitem` MODIFY `state` ENUM('PENDING_PAYMENT', 'WAITING_INSCRIBED_CONFIRMATION', 'WAITING_PAYMENT_CONFIRMATION', 'PAYMENT_CONFIRMED', 'ERROR', 'INSCRIBED') NOT NULL;
