require('dotenv').config()
export default {
    INSCRIPTION_QUEUE_ITEM_EXPIRY_SECONDS: +process.env.INSCRIPTION_QUEUE_ITEM_EXPIRY_SECONDS,

    // payment confirmation worker variables 
    PAYMENT_CONFIRMATION_WORKER_INTERVAL_MS: +process.env.PAYMENT_CONFIRMATION_WORKER_INTERVAL_MS,
    PAYMENT_CONFIRMATION_WORKER_MAX_RECORDS: +process.env.PAYMENT_CONFIRMATION_WORKER_MAX_RECORDS,

    // Inscribe worker variables 
    INSCRIBE_WORKER_INTERVAL_MS: +process.env.INSCRIBE_WORKER_INTERVAL_MS,
    INSCRIBE_WORKER_INSCRIPTIONS_MAX: +process.env.INSCRIBE_WORKER_INSCRIPTIONS_MAX,

    // InscribeStateConfirmationWorker variables
    INSCRIBE_STATE_CONFIRMATION_INTERVAL_MS: +process.env.INSCRIBE_STATE_CONFIRMATION_INTERVAL_MS,
    INSCRIBE_STATE_CONFIRMATION_MAX_RECORDS: +process.env.INSCRIBE_STATE_CONFIRMATION_MAX_RECORDS,
}



    // TXN